from discord.ext.commands import Bot

CLIENT_ID = 00000000000000000
CLIENT_SECRET = "XXXXXXXXXXX"

USERNAME = "Bot#8000"
TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

PREFIX = "!"

BOT = Bot(command_prefix=PREFIX)